services:
  workspace:
    image: mcr.microsoft.com/devcontainers/python:3.0.8-3.10-trixie@sha256:071142a6932dcfc663f6eb188148991f29b6409b3eb8a369f47b004288aaf6f7
    volumes:
      - pulumi:/home/vscode/.pulumi
      - cache:/home/vscode/.cache:delegated
    environment:
      CONTAINER: 1
    healthcheck:
      disable: true

volumes:
  pulumi:
  cache:
