services:
  workspace:
    image: mcr.microsoft.com/devcontainers/base:trixie@sha256:aa263c6fdd7c1bc990eead3922224fe8afbf5d85eaf3b6b9260786ab94d74933
    volumes:
      - pulumi:/home/vscode/.pulumi
      - cache:/home/vscode/.cache:delegated
    healthcheck:
      disable: true

volumes:
  pulumi:
  cache:
