services:
  workspace:
    image: mcr.microsoft.com/devcontainers/python:trixie
    volumes:
      - pulumi:/home/vscode/.pulumi
      - cache:/home/vscode/.cache:delegated
    environment:
      CONTAINER: 1
    healthcheck:
      disable: true

volumes:
  pulumi:
  cache:
